server:
  port: 8081

spring:
  application:
    name: kafka-messaging-server

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      transaction-id-prefix: tx-
    consumer:
      group-id: banking-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: kr.ssok.model
    listener:
      ack-mode: manual

  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        use_sql_comments: 'true'
        format_sql: 'true'
        show_sql: 'true'
    hibernate:
      ddl-auto: update

  datasource:
    username: lgcns
    password: password
    url: jdbc:mariadb://kudong.kr:55023/moni?useUnicode=true&characterEncoding=utf-8&serverTimeZone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver

openbanking:
  kafka:
    request-topic: bank-transfer-requests
    reply-topic: bank-transfer-replies
    timeout: 30000  # 30 seconds timeout for reply